# Étape 1 : Build
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app

# On copie et compile d'abord le shared-models
COPY shared-models /app/shared-models
RUN cd shared-models && mvn clean install -DskipTests

# On copie et compile ensuite le service admin
COPY admin-service /app/admin-service
RUN cd admin-service && mvn clean package -DskipTests

# Étape 2 : Exécution (Image allégée pour la prod)
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/admin-service/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]